//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoWhat.UI.WindowsPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhoWhat.UI.WindowsPhone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBar_Cancel {
            get {
                return ResourceManager.GetString("AppBar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBar_Save {
            get {
                return ResourceManager.GetString("AppBar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who What.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the answer?.
        /// </summary>
        public static string Confirm_RemoveAnswer {
            get {
                return ResourceManager.GetString("Confirm_RemoveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the question?.
        /// </summary>
        public static string Confirm_RemoveQuestion {
            get {
                return ResourceManager.GetString("Confirm_RemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm_Title {
            get {
                return ResourceManager.GetString("Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE.
        /// </summary>
        public static string Feed_Live {
            get {
                return ResourceManager.GetString("Feed_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULAR.
        /// </summary>
        public static string Feed_Popular {
            get {
                return ResourceManager.GetString("Feed_Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNANSWERED.
        /// </summary>
        public static string Feed_Unanswered {
            get {
                return ResourceManager.GetString("Feed_Unanswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Loading....
        /// </summary>
        public static string Loading_Feed {
            get {
                return ResourceManager.GetString("Loading_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection..
        /// </summary>
        public static string Message_NoInternet {
            get {
                return ResourceManager.GetString("Message_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string Message_ServerError {
            get {
                return ResourceManager.GetString("Message_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error occured..
        /// </summary>
        public static string Message_Unspecified {
            get {
                return ResourceManager.GetString("Message_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVITY.
        /// </summary>
        public static string Profile_Activity {
            get {
                return ResourceManager.GetString("Profile_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSWERS.
        /// </summary>
        public static string Profile_Answers {
            get {
                return ResourceManager.GetString("Profile_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        public static string Profile_Info {
            get {
                return ResourceManager.GetString("Profile_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUESTIONS.
        /// </summary>
        public static string Profile_Questions {
            get {
                return ResourceManager.GetString("Profile_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want this application to show toast notifications for rating changes?.
        /// </summary>
        public static string Prompt_Notifications {
            get {
                return ResourceManager.GetString("Prompt_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Prompt_Notifications_Title {
            get {
                return ResourceManager.GetString("Prompt_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Title_AskQuestion {
            get {
                return ResourceManager.GetString("Title_AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Title_Question {
            get {
                return ResourceManager.GetString("Title_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer can not be empty.
        /// </summary>
        public static string Validation_AnswerBodyRequired {
            get {
                return ResourceManager.GetString("Validation_AnswerBodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body must be at least {0} characters; you entered {1}.
        /// </summary>
        public static string Validation_BodyValidationFrmt {
            get {
                return ResourceManager.GetString("Validation_BodyValidationFrmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is required.
        /// </summary>
        public static string Validation_Image {
            get {
                return ResourceManager.GetString("Validation_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question body is required.
        /// </summary>
        public static string Validation_QuestionBodyRequired {
            get {
                return ResourceManager.GetString("Validation_QuestionBodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least one tag.
        /// </summary>
        public static string Validation_TagRequired {
            get {
                return ResourceManager.GetString("Validation_TagRequired", resourceCulture);
            }
        }
    }
}
